### ISSUE TITLE
Unable to sync directory using put

### ISSUE THREAD

**Issue by vkul0960** [18F/s3-resource-simple#30]
I'm new to concourse and found this resource which meets my requirements to sync directory with s3 bucket.
I'm trying to use this to upload entire directory to s3 bucket. I have a task which has a directory as an output and followed by put task. if I use inputs[output from previous task] in the put task I get an error more than one pattern found.
Could you please let me know how do I pass my output(directory) from build task to put task.

Thanks!!

**Comment by afeld** [comment]
Did you figure it out?

**Comment by vkul0960** [comment]
yes thanks I was able to figure out and working fine.
