### ISSUE TITLE
Support IAM Roles

### ISSUE THREAD

**Issue by asceresini** [18F/s3-resource-simple#8]
`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` take precedence over interrogating metadata for role based credentials, regardless of whether they are empty or not.

If you are to rely on a role being applied, then these two environment variables must NOT be defined.

Therefore the following breaks the ability to use IAM roles.

``` bash
export AWS_ACCESS_KEY_ID=$(echo "$payload" | jq -r '.source.access_key_id')
export AWS_SECRET_ACCESS_KEY=$(echo "$payload" | jq -r '.source.secret_access_key')
```

We should only export these environment variables when `source.access_key_id` and source.secret_access_key` are not empty.

I am submitting a Pull Request that addresses this.

## Testing

With regards to testing, open to ideas to test the absence of credentials on a docker image that would mimic a role and access to AWS metadata which you don't have access to in local development.

I have tested this running in Concourse and as stated, if the credential environment variables are not set, then it will gain access through keys retrieved from the metadata service.

**Comment by afeld** [comment]
Closed by #9.
